"""
Report Service
"""

from datetime import datetime
from typing import Optional
from uuid import UUID
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, func

from app.modules.reports.models import Report, ReportStatus, ReportType
from app.common.helpers import generate_random_string


class ReportService:
    def __init__(self, db: AsyncSession):
        self.db = db

    async def generate_report_number(self) -> str:
        return f"RPT{generate_random_string(8, True)}"

    async def create_report(
        self,
        db: AsyncSession,
        report_type: str,
        title: str,
        generated_by: int,
        **kwargs,
    ) -> Report:
        report = Report(
            report_number=await self.generate_report_number(),
            report_type=report_type,
            title=title,
            generated_by=generated_by,
            generated_at=datetime.utcnow(),
            **kwargs,
        )
        db.add(report)
        await db.flush()
        return report

    async def generate_report(
        self,
        report_request,
        user_id: int,
    ) -> Report:
        """Generate a new report based on request"""
        report = Report(
            report_number=await self.generate_report_number(),
            report_type=(
                report_request.report_type.value
                if hasattr(report_request.report_type, "value")
                else report_request.report_type
            ),
            title=report_request.title
            or f"Report {datetime.utcnow().strftime('%Y-%m-%d')}",
            status=ReportStatus.COMPLETED,
            generated_by=user_id,
            generated_at=datetime.utcnow(),
        )
        self.db.add(report)
        await self.db.commit()
        await self.db.refresh(report)
        return report

    async def list_reports(
        self,
        skip: int = 0,
        limit: int = 100,
        report_type: Optional[str] = None,
        status: Optional[str] = None,
    ) -> list[Report]:
        """List all reports with optional filters"""
        query = select(Report)

        if report_type:
            query = query.where(Report.report_type == report_type)
        if status:
            query = query.where(Report.status == status)

        query = query.order_by(Report.generated_at.desc()).offset(skip).limit(limit)

        result = await self.db.execute(query)
        return result.scalars().all()

    async def get_report_by_id(self, report_id: int) -> Optional[Report]:
        """Get a report by ID"""
        result = await self.db.execute(select(Report).where(Report.id == report_id))
        return result.scalar_one_or_none()

    async def delete_report(self, report_id: int, user_id: int) -> bool:
        """Delete a report"""
        report = await self.get_report_by_id(report_id)
        if not report:
            return False
        await self.db.delete(report)
        await self.db.commit()
        return True

    async def get_report_path(self, report_id: int) -> Optional[str]:
        """Get the file path for a report"""
        # In a real implementation, this would return the actual file path
        return None

    async def get_reports_by_user(
        self, user_id: int, skip: int = 0, limit: int = 100
    ) -> list[Report]:
        """Get all reports generated by a user"""
        result = await self.db.execute(
            select(Report)
            .where(Report.generated_by == user_id)
            .order_by(Report.generated_at.desc())
            .offset(skip)
            .limit(limit)
        )
        return result.scalars().all()

    async def generate_lc_summary_report(
        self,
        start_date: str,
        end_date: str,
        user_id: int,
    ) -> Report:
        """Generate Letter of Credit summary report"""
        # For now, create a simple report record
        # In a real implementation, this would aggregate LC data
        report = Report(
            report_number=await self.generate_report_number(),
            report_type=ReportType.LC_SUMMARY.value,
            title=f"LC Summary Report ({start_date} to {end_date})",
            status=ReportStatus.COMPLETED,
            generated_by=user_id,
            generated_at=datetime.utcnow(),
        )
        self.db.add(report)
        await self.db.commit()
        await self.db.refresh(report)
        return report

    async def generate_guarantee_summary_report(
        self,
        start_date: str,
        end_date: str,
        user_id: int,
    ) -> Report:
        """Generate Bank Guarantee summary report"""
        report = Report(
            report_number=await self.generate_report_number(),
            report_type=ReportType.GUARANTEE_SUMMARY.value,
            title=f"Guarantee Summary Report ({start_date} to {end_date})",
            status=ReportStatus.COMPLETED,
            generated_by=user_id,
            generated_at=datetime.utcnow(),
        )
        self.db.add(report)
        await self.db.commit()
        await self.db.refresh(report)
        return report

    async def generate_loan_summary_report(
        self,
        start_date: str,
        end_date: str,
        user_id: int,
    ) -> Report:
        """Generate Trade Loan summary report"""
        report = Report(
            report_number=await self.generate_report_number(),
            report_type=ReportType.LOAN_SUMMARY.value,
            title=f"Loan Performance Report ({start_date} to {end_date})",
            status=ReportStatus.COMPLETED,
            generated_by=user_id,
            generated_at=datetime.utcnow(),
        )
        self.db.add(report)
        await self.db.commit()
        await self.db.refresh(report)
        return report

    async def generate_portfolio_summary_report(
        self,
        as_of_date: str,
        user_id: int,
    ) -> Report:
        """Generate Portfolio summary report (for Collection and Risk Exposure)"""
        report = Report(
            report_number=await self.generate_report_number(),
            report_type=ReportType.PORTFOLIO_SUMMARY.value,
            title=f"Portfolio Summary Report (as of {as_of_date})",
            status=ReportStatus.COMPLETED,
            generated_by=user_id,
            generated_at=datetime.utcnow(),
        )
        self.db.add(report)
        await self.db.commit()
        await self.db.refresh(report)
        return report

    async def generate_compliance_summary_report(
        self,
        start_date: str,
        end_date: str,
        user_id: int,
    ) -> Report:
        """Generate Compliance summary report"""
        report = Report(
            report_number=await self.generate_report_number(),
            report_type=ReportType.COMPLIANCE.value,
            title=f"Compliance Report ({start_date} to {end_date})",
            status=ReportStatus.COMPLETED,
            generated_by=user_id,
            generated_at=datetime.utcnow(),
        )
        self.db.add(report)
        await self.db.commit()
        await self.db.refresh(report)
        return report
